[package]
name = "project"
version = "0.1.0"
authors = ["chenishi <chen.ishi@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7.2"
log = "0.4.8"
env_logger = "0.7.1"
serde = "1.0.103"
serde_json = "1.0.43"